### ISSUE TITLE
[minor?] Error in migrations on fresh database

### ISSUE THREAD

**Issue by antislice** [codeforamerica/citybook#101]
```
{ [SequelizeDatabaseError: column "google_spreadsheet_link" of relation "BookReferences" already exists]
  name: 'SequelizeDatabaseError',
  message: 'column "google_spreadsheet_link" of relation "BookReferences" already exists',
  parent: 
   { [error: column "google_spreadsheet_link" of relation "BookReferences" already exists]
     name: 'error',
     length: 149,
     severity: 'ERROR',
     code: '42701',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'tablecmds.c',
     line: '5069',
     routine: 'check_for_column_name_collision',
     sql: 'ALTER TABLE "public"."BookReferences" ADD COLUMN "google_spreadsheet_link" VARCHAR(255) NOT NULL;' },
```

Reproduction: On an empty database, run `node_modules/.bin/sequelize db:migrate`

Problem: In the `refine-book-references` migration, `google_spreadsheet_link` column is added twice.

Result: the above error, and `refine-book-references` is considered "undone", so future `db:migrate` calls try to run it. (And fail because now the `title` column doesn't exist.) However, all the add/remove columns did happen so if no future migrations are run this won't be an issue.

Solution: Remove duplicate column adds, undo migrations, and rerun. This does erase data.

**Comment by cweems** [comment]
@antislice should work now!
