### ISSUE TITLE
Instructions on How To create a PostgresSQL database

### ISSUE THREAD

**Issue by patrickm02L** [codeforamerica/citybook#102]
I realized that not everyone knows what a PostgresSQL database was or where to download it. 

Perhaps sending them to the link: http://postgresapp.com/ and telling them how to make sure that it's set up and working.

**Comment by patrickm02L** [comment]
Also, since I've never set up a database before. I didn't know that I needed to open psql then use the command. `create database citybook`

**Comment by cweems** [comment]
Updated README with this.
