### ISSUE TITLE
BUG: Extreme latency issues render app unusable on all Android browsers, Firefox for OSX/Windows

### ISSUE THREAD

**Issue by carlvlewis** [codeforamerica/citybook#117]
## Description of issue

While conducting user testing for a [recent fork of CityBook we put together](https://savbook.io) at an [Open Savannah](https://opensavannah.org) brigade meetup, we discovered a strange anomaly: For **all** users on Android devices, regardless of browser, the app appears to be stuck at the loading spinner. Eventually, the app does load, but only after roughly ~8-10 min. of latency, rendering it's basically unusable for the average user. On all iOS browsers, however, the app loads nearly instantly, including on Chrome for iOS. As for desktop performance, in Chrome for OSX and Chrome for Windows 10, the app, too, loads almost instantly, in addition to loading fine in Safari for OSX and Internet Explorer for Windows. *The only browser on desktop to encounter this issue is Firefox.*

Thinking it could possibly be an issue with the data stored in our Google Workbook, we tried opening just the default CityBook demo, and the exact same issues occurred. Interestingly, this issue manifests itself differently in the landing page than it does in the app itself; on the landing page, an [empty iFrame is all you see](http://cvlassets.s3.amazonaws.com/Screen%20Shot%202017-06-10%20at%206.40.36%20PM.png).

## To reproduce:

1. Navigate to [citybook.io](https://citybook.io) on **any** Android mobile phone **OR** on desktop using Firefox in either OSX or Windows OS. 
2. Select `CityBook Demo` to launch the default CityBook app example.
3. Wait 8-10 min. as the loading spinners seem to be stuck, but the app finally loads.

## Possible culprit?

My best guess as to what's causing this to occur is that it's something funky going on with the service workers served up in `sw.js.` 

## Screenshots
![](http://cvlassets.s3.amazonaws.com/Screen%20Shot%202017-06-10%20at%206.40.36%20PM.png)
Landing page as viewed in Firefox on OSX.

## Note to contributors
[Chatham County](http://www.chathamcounty.org/) has expressed interest in adopting and maintaining [SavBook](https://savbook.io), and we've already now missed the date they wanted to launch with an announcement on their homepage and a press release to local media. In addition, the [City of Savannah](http://savannahga.gov) will soon be deciding whether to award a rather large social service grant for its ongoing improvement and maintenance. This would obviously be a big win for CityBook in the wild as a viable solution to the social service directory problem, but unless we solve this issue, it may not come to fruition.

**Comment by cweems** [comment]
Hi @carlvlewis! Thanks for catching this. The browsers effected/nature of the bug do seem to suggest that something is very wrong with the serviceworker. It's quite likely that it's trying to load something from the cache which does not exist and is waiting several minutes to fall back to the network.

I'll modify the serviceworker so that it removes itself, but beware that you may need to hard refresh the app once the change is made in order for the issue to go away. I should be able to do this in the next few hours.

**Comment by carlvlewis** [comment]
Hi @cweems! Thanks for the swift reply and for offering to get this patched for us. Hard refreshing the app shouldn't be an issue; just ping back when you've had a chance to modify the serviceworker or, alternatively, guide me in the direction you think the problem lies. Much appreciated!

**Comment by cweems** [comment]
@joduinn @glassresistor I've fixed this issue but I've been removed from the Code for America organization so I don't have write access. Would you mind changing that?

**Comment by carlvlewis** [comment]
But it'd be much easier if this were merged. 👍

**Comment by carlvlewis** [comment]
Closing as this issue has been resolved, but we probably should find a way to add back the serviceworker for performance reasons without it causing trouble in certain mobile browsers and all Firefox browsers.
